### ISSUE TITLE
не работает

### ISSUE THREAD

**Issue by profilemyprofile** [evtn/vk_py#2]
а нет работает

**Comment by ShellarFX** [comment]
срочно

**Comment by evtn** [comment]
можете привести ошибки

а, хорошо, рад что заработало!

**Comment by ub1x** [comment]
спасибо

**Comment by profilemyprofile** [comment]
> спасибо

спасибо в карман не положишь

**Comment by evtn** [comment]
> > спасибо
> 
> спасибо в карман не положишь

попробуйте обновить ваше спасибо, две версии назад добавили эту возможность

**Comment by profilemyprofile** [comment]
> > > спасибо
> > 
> > 
> > спасибо в карман не положишь
> 
> попробуйте обновить ваше спасибо, две версии назад добавили эту возможность

тогда спасибо

**Comment by profilemyprofile** [comment]
обновите доку**мент**ацию

**Comment by evtn** [comment]
> обновите доку**мент**ацию

**я** в **бл**ижайшее время сделаю это об**я**зательно, по**д**ождите пят**ь** лет.

**Comment by ShellarFX** [comment]
> > обновите доку**мент**ацию
> 
> **я** в **бл**ижайшее время сделаю это об**я**зательно, по**д**ождите пят**ь** лет.

Самокритично, что могу сказать
